### ISSUE TITLE
'VoidCallback' isn't a type

### ISSUE THREAD

**Issue by Emmanuelfrimpong** [Crdzbird/flowder#9]
i get this error on build 
.
Error: Type 'VoidCallback' not found.
../…/utils/downloader_utils.dart:23
  final VoidCallback onDone;
        ^^^^^^^^^^^^
: Error: 'VoidCallback' isn't a type.
../…/utils/downloader_utils.dart:23
  final VoidCallback onDone;
        ^^^^^^^^^^^^

**Comment by murali-cse** [comment]
I am also got the same error! 

I am using 

flowder: ^0.2.0
flutter version : 2.5.3

**Comment by murali-cse** [comment]
![image](https://user-images.githubusercontent.com/63541419/141772418-f783c060-cd66-4f83-bb81-98768e998bc4.png)

idk, is this correct or not ! but It's working for me after  I add <b>typedef VoidCallback = void Function();</b> line on flowder.dart

**Comment by mapacheverdugo** [comment]
Fixed on #10

**Comment by alexaung** [comment]
I am facing same issue. how do you guys solved this issue.

**Comment by koundal691** [comment]
any update on this issue ?

**Comment by Livekus** [comment]
#10 not work for me. i clone to local directory, add it to pubspec ../flowder still not work

**Comment by Harsh223** [comment]
> #10 not work for me. i clone to local directory, add it to pubspec ../flowder still not work

Fixed on #12

**Comment by Harsh223** [comment]
@Livekus @alexaung @koundal691 Before the dev accepts my pull request you can use my fork of the repo instead

How to do that?
i) Open your pubspec.yaml file
ii) Comment/remove the line flowder: ^0.2.0
iii) and replace it with:
  flowder:
    git:
      url: https://github.com/Harsh223/flowder.git

iv) run flutter pub get
v) build it again and it should have fixed it.

**Comment by Livekus** [comment]
@Harsh223  Thank you very much , i got some solution before, just change final VoidCallback onDone; to dynamic form which is final onDone;  but your solution may be better.

**Comment by Nicole-xq** [comment]
> 我在构建时收到此错误 。 错误：找不到类型“VoidCallback”。 ../…/utils/downloader_utils.dart:23 最后的 VoidCallback onDone; ^^^^^^^^^^^^ ：错误：“VoidCallback”不是一个类型。 ../…/utils/downloader_utils.dart:23 最后的 VoidCallback onDone; ^^^^^^^^^^^^^

This problem occurs because the dart:ui package has not been introduced.
Add the following code to the downloader_utils.dart file and it will run successfully
import 'dart:ui';

**Comment by Tahira6020** [comment]
> ![image](https://user-images.githubusercontent.com/63541419/141772418-f783c060-cd66-4f83-bb81-98768e998bc4.png)
> 
> idk, is this correct or not ! but It's working for me after I add typedef VoidCallback = void Function(); line on flowder.dart

Thank you, I added this line and error eliminated

**Comment by Tahira6020** [comment]
> ![image](https://user-images.githubusercontent.com/63541419/141772418-f783c060-cd66-4f83-bb81-98768e998bc4.png)
> 
> idk, is this correct or not ! but It's working for me after I add typedef VoidCallback = void Function(); line on flowder.dart

Thank you, I added this line and error eliminated
